import { StyleSheet } from "react-native";

import { tokens } from "@/theme/tokens";

export const authorScreenStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: tokens.colors.bg,
  },

  topBar: {
    paddingTop: tokens.space.xs,
    paddingHorizontal: tokens.space.md,
    paddingBottom: tokens.space.xs,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  topBarSpacer: {
    width: 40,
    height: 40,
  },

  listContent: {
    width: "100%",
    maxWidth: 393,
    alignSelf: "center",
    paddingHorizontal: 24,
    paddingBottom: tokens.space.xl,
  },

  profileCard: {
    marginTop: tokens.space.sm,
    paddingHorizontal: 20,
    paddingVertical: 22,
    borderRadius: 28,
    backgroundColor: tokens.colors.surface,
    borderWidth: 1,
    borderColor: tokens.colors.border,
    position: "relative",
    overflow: "hidden",
    gap: 13,
    shadowColor: tokens.shadow.color,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  profilePaperWash: {
    position: "absolute",
    top: 18,
    right: 18,
    width: 112,
    height: 74,
    borderRadius: 18,
    opacity: 0.42,
    transform: [{ rotate: "-5deg" }],
  },
  profilePaperLine: {
    position: "absolute",
    height: 1,
    opacity: 0.32,
  },
  profilePaperLineTop: {
    top: 86,
    left: 24,
    right: 62,
  },
  profilePaperLineBottom: {
    bottom: 42,
    left: 82,
    right: 24,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: tokens.space.md as any,
    paddingRight: 54,
  },
  profileHeaderWithLeftSticker: {
    paddingTop: 18,
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontSize: 21,
    fontWeight: "900",
    color: tokens.colors.green700,
  },
  identityBlock: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  profileKicker: {
    fontSize: 12,
    color: tokens.colors.textMuted,
    fontWeight: "800",
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: tokens.space.xs as any,
  },
  name: {
    fontSize: 25,
    fontWeight: "900",
    color: tokens.colors.text,
    flexShrink: 1,
  },
  badgeEmoji: {
    fontSize: 22,
    lineHeight: 26,
  },
  bio: {
    fontSize: tokens.font.body,
    color: tokens.colors.textMuted,
    lineHeight: 22,
  },
  inlineActionBtn: {
    alignSelf: "flex-start",
    marginTop: -2,
  },
  inlineActionText: {
    fontSize: tokens.font.small,
    color: tokens.colors.green700,
    fontWeight: "800",
  },
  profileBackgroundLabel: {
    alignSelf: "flex-start",
    borderRadius: tokens.radius.pill,
    backgroundColor: "rgba(255,255,255,0.55)",
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: tokens.font.small,
    color: tokens.colors.green900,
    fontWeight: "900",
    overflow: "hidden",
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  statText: {
    fontSize: 12,
    color: tokens.colors.textMuted,
    fontWeight: "900",
  },
  statMetric: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  joinedAt: {
    fontSize: tokens.font.small,
    color: tokens.colors.textFaint,
  },
  showcaseRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: tokens.space.xs as any,
  },
  showcaseChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: tokens.radius.pill,
    borderWidth: 1,
    borderColor: "rgba(63,122,76,0.22)",
    backgroundColor: "rgba(255,255,255,0.66)",
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  showcaseEmoji: {
    fontSize: 13,
    lineHeight: 16,
  },
  showcaseText: {
    fontSize: tokens.font.small,
    color: tokens.colors.green700,
    fontWeight: "700",
  },
  stickerOverlay: {
    position: "absolute",
    width: 28,
    height: 28,
    borderRadius: tokens.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: tokens.colors.borderStrong,
    backgroundColor: "rgba(255,255,255,0.78)",
    shadowColor: tokens.shadow.color,
    shadowOpacity: tokens.shadow.opacity,
    shadowRadius: tokens.shadow.radius,
    shadowOffset: { width: 0, height: tokens.shadow.offsetY },
    elevation: 2,
  },
  stickerTL: {
    top: 13,
    left: 14,
  },
  stickerTR: {
    top: 13,
    right: 14,
  },
  stickerBR: {
    bottom: 14,
    right: 14,
  },
  stickerText: {
    fontSize: 14,
    lineHeight: 16,
  },
  profileCustomizeBtn: {
    flexGrow: 1,
    borderRadius: tokens.radius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.green700,
    backgroundColor: tokens.colors.green050,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: "center",
  },
  profileCustomizeBtnText: {
    fontSize: tokens.font.small,
    fontWeight: "900",
    color: tokens.colors.green700,
  },
  primaryActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignSelf: "flex-start",
  },
  latestPostBtn: {
    flexGrow: 1,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.colors.green700,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: "center",
  },
  latestPostBtnText: {
    fontSize: tokens.font.small,
    fontWeight: "900",
    color: "#fff",
  },
  followBtn: {
    borderRadius: tokens.radius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.green700,
    backgroundColor: tokens.colors.green700,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  followBtnActive: {
    backgroundColor: tokens.colors.green050,
    borderColor: tokens.colors.green700,
  },
  followBtnDisabled: {
    opacity: 0.6,
  },
  followBtnText: {
    fontSize: tokens.font.small,
    fontWeight: "900",
    color: tokens.colors.textInverse,
  },
  followBtnTextActive: {
    color: tokens.colors.green700,
  },
  shareBtn: {
    borderRadius: tokens.radius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.border,
    backgroundColor: tokens.colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  shareBtnText: {
    fontSize: tokens.font.small,
    fontWeight: "900",
    color: tokens.colors.text,
  },
  overflowCard: {
    alignSelf: "stretch",
    borderWidth: 1,
    borderColor: tokens.colors.border,
    borderRadius: 18,
    backgroundColor: tokens.colors.surface,
    overflow: "hidden",
  },
  overflowItem: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.border,
  },
  overflowItemText: {
    fontSize: tokens.font.small,
    fontWeight: "800",
    color: tokens.colors.text,
  },
  sectionRow: {
    marginTop: 16,
    marginBottom: tokens.space.sm,
    gap: 10,
  },
  sectionLabel: {
    fontSize: tokens.font.small,
    fontWeight: "800",
    color: tokens.colors.textFaint,
    letterSpacing: -0.2,
  },
  sortRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: tokens.space.xs as any,
  },
  sortChip: {
    minHeight: 31,
    borderRadius: tokens.radius.pill,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: tokens.colors.borderStrong,
    backgroundColor: tokens.colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  sortChipActive: {
    backgroundColor: tokens.colors.green050,
    borderColor: tokens.colors.green700,
  },
  sortChipText: {
    fontSize: tokens.font.small,
    fontWeight: "700",
    color: tokens.colors.textMuted,
  },
  sortChipTextActive: {
    color: tokens.colors.green900,
  },
  listItemSpacer: {
    height: tokens.space.md,
  },
  listFooter: {
    paddingVertical: tokens.space.lg,
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: tokens.space.xl,
    gap: tokens.space.sm as any,
  },
});
