import { StyleSheet } from "react-native";
import { tokens } from "@/theme/tokens";

/**
 * PostDetail Screen styles (tokens 기반)
 * - Screen은 조립자 역할만 하도록, 스타일은 여기로 집결
 */

export function createPostDetailStyles(actionBarHeight: number, topInset = 0) {
  const contentBottomPad = actionBarHeight + tokens.space.xl;
  const topBarPaddingTop = Math.max(tokens.space.md, topInset + tokens.space.xs);

  return StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: tokens.colors.bg,
      position: "relative",
    },

    // --- Header ---
    topBar: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      zIndex: 40,
      paddingTop: topBarPaddingTop,
      paddingHorizontal: tokens.space.sm,
      paddingBottom: tokens.space.xs,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    rightActionBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
      borderWidth: 0,
      borderColor: "transparent",
    },

    topBarSpacer: {
      width: 40,
      height: 40,
    },

    // --- Scroll ---
    scrollContent: {
      width: "100%",
      maxWidth: 393,
      alignSelf: "center",
      paddingHorizontal: 0,
      paddingTop: 0,
      paddingBottom: contentBottomPad,
    },
    detailMetaBlock: {
      marginTop: tokens.space.md,
      marginBottom: tokens.space.lg,
      paddingHorizontal: tokens.space.md,
      gap: tokens.space.sm as any,
    },
    introWrap: {
      marginTop: 2,
      marginBottom: tokens.space.md,
      gap: 4,
    },
    introEyebrow: {
      fontSize: 11,
      letterSpacing: 1.3,
      fontWeight: "900",
      color: tokens.colors.textFaint,
    },
    metaRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    metaAuthor: {
      fontSize: 13,
      fontWeight: "800",
      color: tokens.colors.text,
    },
    metaAuthorPress: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    metaAuthorPhoto: {
      width: 24,
      height: 24,
      borderRadius: 9,
      backgroundColor: tokens.colors.surfaceStrong,
      borderWidth: 1,
      borderColor: tokens.colors.border,
    },
    metaDot: {
      fontSize: 13,
      fontWeight: "700",
      color: tokens.colors.textFaint,
    },
    metaDate: {
      fontSize: 13,
      fontWeight: "700",
      color: tokens.colors.textMuted,
    },

    // --- Meta bar ---
    metaBar: {
      marginTop: 0,
      marginBottom: tokens.space.md,
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: tokens.space.sm as any,
    },
    typeChip: {
      paddingHorizontal: tokens.space.sm,
      paddingVertical: 7,
      borderRadius: tokens.radius.pill,
      backgroundColor: tokens.colors.surfaceStrong,
      borderWidth: 1,
      borderColor: tokens.colors.border,
    },
    typeChipText: {
      fontSize: 12,
      fontWeight: "800",
      color: tokens.colors.text,
      letterSpacing: -0.2,
    },
    tagChip: {
      paddingHorizontal: tokens.space.sm,
      paddingVertical: 7,
      borderRadius: tokens.radius.pill,
      backgroundColor: tokens.colors.surface,
      borderWidth: 1,
      borderColor: tokens.colors.border,
    },
    tagChipText: {
      fontSize: 12,
      fontWeight: "700",
      color: tokens.colors.textMuted,
      letterSpacing: -0.2,
    },
    relatedSection: {
      marginTop: tokens.space.xl,
      paddingHorizontal: tokens.space.md,
      paddingTop: tokens.space.lg,
      paddingBottom: tokens.space.xl,
      gap: tokens.space.sm as any,
      backgroundColor: tokens.colors.bgMuted,
      borderTopWidth: 1,
      borderTopColor: tokens.colors.border,
    },
    relatedEyebrow: {
      fontSize: 11,
      fontWeight: "900",
      color: tokens.colors.textFaint,
      letterSpacing: 0,
      marginBottom: -4,
    },
    relatedTitle: {
      fontSize: 16,
      fontWeight: "900",
      color: tokens.colors.text,
    },
    relatedHint: {
      fontSize: tokens.font.small,
      color: tokens.colors.textMuted,
      fontWeight: "700",
    },
    relatedList: {
      gap: tokens.space.sm as any,
    },
    relatedFeedCard: {
      minHeight: 112,
      borderRadius: tokens.radius.lg,
      borderWidth: 1,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.surface,
      padding: tokens.space.sm,
      flexDirection: "row",
      alignItems: "center",
      gap: tokens.space.md as any,
    },
    relatedFeedCardPressed: {
      opacity: 0.78,
    },
    relatedThumbWrap: {
      width: 72,
      height: 92,
      borderRadius: tokens.radius.md,
      overflow: "hidden",
      backgroundColor: "#f7f3ea",
      borderWidth: 1,
      borderColor: tokens.colors.border,
    },
    relatedThumb: {
      width: "100%",
      height: "100%",
      backgroundColor: "#f7f3ea",
    },
    relatedThumbFallback: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: tokens.colors.green050,
    },
    relatedFeedCopy: {
      flex: 1,
      minWidth: 0,
      gap: 5,
    },
    relatedFeedAuthor: {
      fontSize: 12,
      fontWeight: "900",
      color: tokens.colors.textMuted,
    },
    relatedFeedTitle: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: "900",
      color: tokens.colors.text,
    },
    relatedFeedMeta: {
      fontSize: 12,
      fontWeight: "800",
      color: tokens.colors.green700,
    },
    relatedFeedMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    relatedCard: {
      borderWidth: 1,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radius.lg,
      backgroundColor: tokens.colors.surfaceStrong,
      padding: tokens.space.md,
      gap: 6,
    },
    relatedCardTitle: {
      fontSize: 14,
      fontWeight: "800",
      color: tokens.colors.text,
    },
    relatedCardExcerpt: {
      fontSize: tokens.font.small,
      color: tokens.colors.textMuted,
      lineHeight: 20,
    },
    relatedCardMeta: {
      fontSize: tokens.font.small,
      color: tokens.colors.textFaint,
      fontWeight: "700",
    },
    commentSection: {
      marginTop: tokens.space.xl,
      paddingHorizontal: tokens.space.md,
      gap: tokens.space.md as any,
    },
    permissionRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: tokens.space.xs as any,
      marginTop: tokens.space.sm,
    },
    permissionChip: {
      borderWidth: 1,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radius.pill,
      backgroundColor: tokens.colors.surfaceStrong,
      paddingHorizontal: tokens.space.sm,
      paddingVertical: 6,
    },
    permissionChipText: {
      fontSize: 12,
      fontWeight: "800",
      color: tokens.colors.textMuted,
    },
    commentHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: tokens.space.sm as any,
    },
    commentHeaderActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flexShrink: 0,
    },
    commentIconBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: tokens.colors.green050,
      borderWidth: 1,
      borderColor: tokens.colors.border,
    },
    commentSheetOverlay: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: tokens.colors.overlay,
    },
    commentKeyboardAvoider: {
      flex: 1,
    },
    commentDismissLayer: {
      ...StyleSheet.absoluteFillObject,
    },
    commentKeyboardCornerFill: {
      position: "absolute",
      left: -2,
      right: -2,
      bottom: -58,
      height: 58,
      backgroundColor: "#26272a",
    },
    commentSheet: {
      width: "100%",
      maxHeight: "82%",
      backgroundColor: tokens.colors.surface,
      borderTopLeftRadius: tokens.radius.xl,
      borderTopRightRadius: tokens.radius.xl,
      borderWidth: 1,
      borderColor: tokens.colors.border,
      paddingHorizontal: tokens.space.lg,
      paddingTop: tokens.space.sm,
      paddingBottom: tokens.space.lg,
    },
    commentSheetHandle: {
      width: 42,
      height: 5,
      borderRadius: tokens.radius.pill,
      backgroundColor: tokens.colors.borderStrong,
      alignSelf: "center",
      marginBottom: tokens.space.md,
    },
    commentSheetContent: {
      paddingTop: tokens.space.md,
      paddingBottom: tokens.space.xl,
      gap: tokens.space.md as any,
    },
    commentTitle: {
      fontSize: 16,
      fontWeight: "900",
      color: tokens.colors.text,
    },
    commentKicker: {
      fontSize: 11,
      fontWeight: "900",
      color: tokens.colors.textFaint,
      letterSpacing: 0,
      marginBottom: 3,
    },
    commentComposer: {
      borderWidth: 1,
      borderColor: tokens.colors.borderStrong,
      borderRadius: tokens.radius.lg,
      backgroundColor: tokens.colors.surface,
      padding: tokens.space.md,
      gap: tokens.space.sm as any,
    },
    replyTargetRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: tokens.space.sm as any,
      paddingHorizontal: tokens.space.sm,
      paddingVertical: tokens.space.xs,
      borderRadius: tokens.radius.md,
      backgroundColor: tokens.colors.green050,
    },
    replyTargetText: {
      flex: 1,
      fontSize: tokens.font.small,
      fontWeight: "800",
      color: tokens.colors.green900,
    },
    replyCancelText: {
      fontSize: tokens.font.small,
      fontWeight: "900",
      color: tokens.colors.textMuted,
    },
    commentInput: {
      minHeight: 76,
      maxHeight: 150,
      borderWidth: 1,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radius.md,
      backgroundColor: tokens.colors.bgMuted,
      paddingHorizontal: tokens.space.md,
      paddingVertical: tokens.space.sm,
      color: tokens.colors.text,
      fontSize: tokens.font.body,
      lineHeight: 21,
      textAlignVertical: "top",
    },
    commentComposerFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: tokens.space.sm as any,
    },
    commentInputCount: {
      fontSize: tokens.font.small,
      fontWeight: "700",
      color: tokens.colors.textFaint,
    },
    commentSubmitBtn: {
      minWidth: 86,
      borderRadius: tokens.radius.md,
      backgroundColor: tokens.colors.green900,
      alignItems: "center",
      paddingHorizontal: tokens.space.md,
      paddingVertical: 10,
    },
    commentSubmitBtnDisabled: {
      opacity: 0.45,
    },
    commentSubmitText: {
      fontSize: tokens.font.small,
      fontWeight: "900",
      color: tokens.colors.textInverse,
    },
    commentLoadingRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: tokens.space.sm as any,
      paddingVertical: tokens.space.md,
    },
    commentEmptyBox: {
      borderWidth: 1,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radius.lg,
      backgroundColor: tokens.colors.surfaceStrong,
      padding: tokens.space.md,
    },
    commentHint: {
      fontSize: tokens.font.small,
      fontWeight: "700",
      color: tokens.colors.textMuted,
      lineHeight: 20,
    },
    commentList: {
      gap: tokens.space.md as any,
    },
    commentThread: {
      gap: tokens.space.sm as any,
    },
    commentItem: {
      borderWidth: 1,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radius.lg,
      backgroundColor: tokens.colors.surfaceStrong,
      padding: tokens.space.md,
      gap: 8,
    },
    replyList: {
      marginLeft: tokens.space.lg,
      gap: tokens.space.sm as any,
    },
    replyItem: {
      borderWidth: 1,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radius.md,
      backgroundColor: tokens.colors.bgMuted,
      padding: tokens.space.md,
      gap: 8,
    },
    commentMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: tokens.space.sm as any,
    },
    commentAuthorWrap: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      gap: tokens.space.sm as any,
    },
    commentMarker: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: tokens.colors.green700,
      backgroundColor: tokens.colors.surface,
    },
    replyMarker: {
      width: 30,
      height: 30,
      borderRadius: 15,
    },
    commentMarkerText: {
      fontSize: 12,
      fontWeight: "900",
      color: tokens.colors.green700,
    },
    commentAuthor: {
      flex: 1,
      fontSize: tokens.font.small,
      fontWeight: "900",
      color: tokens.colors.text,
    },
    commentDate: {
      fontSize: 12,
      fontWeight: "700",
      color: tokens.colors.textFaint,
    },
    commentBody: {
      fontSize: tokens.font.body,
      lineHeight: 22,
      color: tokens.colors.text,
    },
    commentActionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: tokens.space.md as any,
    },
    commentIconAction: {
      minHeight: 30,
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    commentActionText: {
      fontSize: tokens.font.small,
      fontWeight: "900",
      color: tokens.colors.green700,
    },
    commentActionTextActive: {
      color: tokens.colors.green700,
    },
    commentDangerText: {
      fontSize: tokens.font.small,
      fontWeight: "900",
      color: tokens.colors.danger,
    },

    // --- Action bar (fixed) ---
    actionsBar: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 30,
      elevation: 16,
      paddingHorizontal: tokens.space.xl,
      backgroundColor: tokens.colors.surface,
      borderTopWidth: 1,
      borderTopColor: tokens.colors.borderStrong,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
      shadowColor: tokens.shadow.color,
      shadowOpacity: Math.max(tokens.shadow.opacity * 0.6, 0.08),
      shadowRadius: tokens.shadow.radius,
      shadowOffset: { width: 0, height: -Math.max(tokens.shadow.offsetY, 4) },
    },
    actionBtn: {
      alignItems: "center",
      justifyContent: "center",
      gap: tokens.space.xs as any,
      transform: [{ translateY: 5 }],
    },
    actionLabel: {
      fontSize: tokens.font.small,
      fontWeight: "700",
      color: tokens.colors.textMuted,
    },
    actionLabelActive: {
      color: tokens.colors.green700,
    },

    // --- States ---
    center: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: tokens.space.xl,
      gap: tokens.space.sm as any,
    },

    // --- Bookmark modal ---
    bookmarkModalOverlay: {
      flex: 1,
      backgroundColor: tokens.colors.overlay,
      justifyContent: "center",
      alignItems: "center",
      padding: 18,
    },
    bookmarkModalCard: {
      width: "100%",
      maxWidth: 420,
      backgroundColor: tokens.colors.white,
      borderRadius: tokens.radius.lg,
      borderWidth: 1,
      borderColor: tokens.colors.borderStrong,
      padding: tokens.space.lg,
    },
    bookmarkModalTitle: {
      fontSize: 16,
      fontWeight: "900",
      color: tokens.colors.text,
    },
    bookmarkModalDescription: {
      marginTop: 8,
      fontSize: tokens.font.small,
      color: tokens.colors.textMuted,
      fontWeight: "700",
    },
    shareModalProgressRow: {
      marginTop: 14,
      borderRadius: tokens.radius.md,
      borderWidth: 1,
      borderColor: tokens.colors.green100,
      backgroundColor: tokens.colors.green050,
      paddingHorizontal: tokens.space.md,
      paddingVertical: tokens.space.sm,
      flexDirection: "row",
      alignItems: "center",
      gap: tokens.space.sm as any,
    },
    shareModalProgressText: {
      flex: 1,
      color: tokens.colors.green900,
      fontSize: 13,
      fontWeight: "800",
    },
    shareBlockingOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.42)",
      alignItems: "center",
      justifyContent: "center",
      padding: tokens.space.xl,
    },
    shareBlockingCard: {
      width: "100%",
      maxWidth: 320,
      borderRadius: tokens.radius.lg,
      borderWidth: 1,
      borderColor: tokens.colors.borderStrong,
      backgroundColor: tokens.colors.surfaceStrong,
      paddingHorizontal: tokens.space.xl,
      paddingVertical: tokens.space.xl,
      alignItems: "center",
      gap: tokens.space.sm as any,
    },
    shareBlockingTitle: {
      marginTop: tokens.space.sm,
      color: tokens.colors.text,
      fontSize: 16,
      fontWeight: "900",
    },
    shareBlockingText: {
      color: tokens.colors.textMuted,
      fontSize: tokens.font.small,
      fontWeight: "700",
      lineHeight: 19,
      textAlign: "center",
    },
    shareSignatureToggle: {
      marginTop: 14,
      borderRadius: tokens.radius.md,
      borderWidth: 1,
      borderColor: tokens.colors.green100,
      backgroundColor: tokens.colors.green050,
      paddingHorizontal: tokens.space.md,
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: tokens.space.sm as any,
    },
    shareSignatureTextWrap: {
      flex: 1,
      minWidth: 0,
    },
    shareSignatureTitle: {
      color: tokens.colors.green900,
      fontSize: tokens.font.small,
      fontWeight: "900",
    },
    shareSignatureHint: {
      marginTop: 3,
      color: tokens.colors.textMuted,
      fontSize: 12,
      fontWeight: "700",
    },
    valuePill: {
      borderRadius: tokens.radius.pill,
      paddingHorizontal: 8,
      paddingVertical: 4,
      backgroundColor: tokens.colors.surface,
      borderWidth: 1,
      borderColor: tokens.colors.green100,
    },
    valuePillText: {
      color: tokens.colors.green700,
      fontSize: 10,
      fontWeight: "900",
    },
    modalActionList: {
      marginTop: 16,
      gap: 10,
    },
    modalActionBtn: {
      borderRadius: tokens.radius.lg,
      borderWidth: 1,
      borderColor: tokens.colors.borderStrong,
      backgroundColor: tokens.colors.surfaceStrong,
      alignItems: "center",
      paddingVertical: 13,
      paddingHorizontal: tokens.space.md,
    },
    modalActionBtnDanger: {
      borderColor: tokens.colors.dangerBorder,
      backgroundColor: tokens.colors.dangerSoft,
    },
    modalActionBtnGhost: {
      backgroundColor: tokens.colors.surface,
    },
    modalActionText: {
      fontSize: tokens.font.small,
      fontWeight: "800",
      color: tokens.colors.text,
    },
    modalActionTextDanger: {
      color: tokens.colors.danger,
    },
    bookmarkModalLoadingWrap: {
      marginTop: 14,
    },
    bookmarkModalLoadingText: {
      fontSize: 13,
      color: tokens.colors.textMuted,
      fontWeight: "700",
    },
    bookmarkModalEmptyWrap: {
      marginTop: 14,
      gap: tokens.space.sm as any,
    },
    bookmarkModalEmptyText: {
      fontSize: 13,
      color: tokens.colors.textMuted,
      fontWeight: "700",
    },
    bookmarkModalCreateBtn: {
      borderRadius: 12,
      backgroundColor: tokens.colors.green900,
      alignItems: "center",
      paddingVertical: 11,
    },
    bookmarkModalCreateBtnText: {
      color: tokens.colors.textInverse,
      fontSize: 13,
      fontWeight: "900",
    },
    bookmarkModalList: {
      marginTop: 14,
      gap: 8,
    },
    bookmarkModalListItem: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: tokens.colors.borderStrong,
      backgroundColor: tokens.colors.white,
      paddingHorizontal: 12,
      paddingVertical: 10,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    bookmarkModalListItemActive: {
      borderColor: tokens.colors.green900,
      backgroundColor: tokens.colors.green100,
    },
    bookmarkModalListItemDisabled: {
      opacity: 0.55,
    },
    bookmarkModalListItemName: {
      color: tokens.colors.text,
      fontSize: 13,
      fontWeight: "800",
    },
    bookmarkModalListItemStatus: {
      color: tokens.colors.textMuted,
      fontSize: tokens.font.small,
      fontWeight: "700",
    },
    bookmarkModalCloseBtn: {
      marginTop: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: tokens.colors.borderStrong,
      alignItems: "center",
      paddingVertical: 10,
      backgroundColor: tokens.colors.bgMuted,
    },
    bookmarkModalCloseBtnText: {
      color: tokens.colors.text,
      fontSize: 13,
      fontWeight: "900",
    },
  });
}
