import type { TextStyle } from "react-native";

export const appFontFamily = {
  regular: "IBMPlexSansKR-Medium",
  medium: "IBMPlexSansKR-Medium",
  semibold: "IBMPlexSansKR-Medium",
  ui: "IBMPlexSansKR-Medium",
  editorial: "Hahmlet-Regular",
  editorialMedium: "Hahmlet-Medium",
  editorialStrong: "Hahmlet-SemiBold",
  handwriting: "Gaegu-Regular",
} as const;

export const typography = {
  brand: {
    fontFamily: appFontFamily.editorialStrong,
    fontSize: 28,
    lineHeight: 38,
    letterSpacing: -0.7,
    fontWeight: "600",
  },
  display: {
    fontFamily: appFontFamily.editorialStrong,
    fontSize: 30,
    lineHeight: 42,
    letterSpacing: -0.75,
    fontWeight: "600",
  },
  heroQuote: {
    fontFamily: appFontFamily.editorialMedium,
    fontSize: 23,
    lineHeight: 37,
    letterSpacing: -0.45,
    fontWeight: "500",
  },
  sectionTitle: {
    fontFamily: appFontFamily.ui,
    fontSize: 18,
    lineHeight: 27,
    letterSpacing: -0.35,
    fontWeight: "500",
  },
  cardTitle: {
    fontFamily: appFontFamily.medium,
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: -0.35,
    fontWeight: "500",
  },
  tabLabel: {
    fontFamily: appFontFamily.medium,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: -0.25,
    fontWeight: "500",
  },
  author: {
    fontFamily: appFontFamily.regular,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: -0.1,
    fontWeight: "400",
  },
  meta: {
    fontFamily: appFontFamily.regular,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: -0.1,
    fontWeight: "400",
  },
  excerpt: {
    fontFamily: appFontFamily.editorial,
    fontSize: 17,
    lineHeight: 30,
    letterSpacing: -0.1,
    fontWeight: "400",
  },
  actionMeta: {
    fontFamily: appFontFamily.regular,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: -0.1,
    fontWeight: "400",
  },
  pageTitle: {
    fontFamily: appFontFamily.ui,
    fontSize: 23,
    lineHeight: 32,
    letterSpacing: -0.4,
    fontWeight: "500",
  },
  eyebrow: {
    fontFamily: appFontFamily.regular,
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.2,
    fontWeight: "400",
  },
  uiBody: {
    fontFamily: appFontFamily.regular,
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: -0.15,
    fontWeight: "400",
  },
  action: {
    fontFamily: appFontFamily.medium,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: -0.15,
    fontWeight: "500",
  },
} satisfies Record<string, TextStyle>;
